# Build stage

FROM maven:3.9.12-eclipse-temurin-21-alpine AS builder

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

# Run stage
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=builder /app/target/deployment-tester-1.0-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]

